replicaCount: 2

output:
  host: 'elasticsearch-client'

service:
  ports:
    - name: "monitor-agent"
      protocol: TCP
      containerPort: 24220
    - name: "forward"
      protocol: TCP
      containerPort: 24224
