debug: False

metalk8s_storage_addon_dir: '{{ kube_config_dir }}/addons/storage_lvm'

# Set default LVm VGs storageclass and hostpath
metalk8s_storageclass_vg_metalk8s: 'local-lvm'
metalk8s_storageclass_default_vg_metalk8s: True
metalk8s_host_path_vg_metalk8s: '/mnt/vg_metalk8s'

# Check vg metalk8s_lvm_extra_vgs in setup_lvm_vg role
# if the variable exists
# metalk8s_storageclass_<vg>: 'my-new-storage-class'
# metalk8s_host_path_<vg>: '/mnt/myhostpath'
