- name: 'wait for helm to be deployed'
  command: '{{ bin_dir }}/helm version'
  register: helm_version
  until: not helm_version|failed
  retries: 50
  delay: 10
  changed_when: False
  check_mode: False
  run_once: True
  delegate_to: "{{ groups['kube-master'][0] }}"
