docker_dns_servers_strict: False
kube_basic_auth: True
kubeconfig_localhost: True

dns_mode: 'coredns'
kube_proxy_mode: 'ipvs'

kube_version: 'v1.10.11'

# Request usage of the `overlay2` storage driver, even on pre-18.03 Docker
# installs.
# Whilst this is not guaranteed to work on 'old' kernels, we check whether we're
# running CentOS 7.4 or higher, with a kernel which contains all required
# backports.
docker_storage_options: -s overlay2 --storage-opt overlay2.override_kernel_check=true

# Enable Calico Prometheus monitoring
calico_felix_prometheusmetricsenabled: 'true'
