apiVersion: v1
kind: Pod
metadata:
  name: "metalk8s-integration-tests-ui"
spec:
  containers:
  - name: worker
    image: {{ images['worker'] }}
    resources:
      requests:
        cpu: 1500m
        memory: 2Gi
      limits:
        cpu: '2'
        memory: 3Gi
    command: ["/bin/sh"]
    args: ["-c", "buildbot-worker create-worker . ${BUILDMASTER}:${BUILDMASTER_PORT} ${WORKERNAME} ${WORKERPASS} && buildbot-worker start --nodaemon"]
    volumeMounts:
      - name: worker-workspace
        mountPath: /home/eve/workspace
  - name: application
    image: {{ images['application'] }}
    resources:
      requests:
        cpu: 250m
        memory: 200Mi
      limits:
        cpu: 350m
        memory: 300Mi
    command: ["nginx"]
    args: ["-g", "daemon off;"]
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
  volumes:
    - name: worker-workspace
      emptyDir: {}
