---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install packages required to test this role
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - iproute
