# The role default variable are not present in hostvars[inventory_hostname]
# https://github.com/ansible/ansible/issues/6189
# We then rely on "vars" which "works" but not happy about it
- name: "Setup MetalK8S Storage: Check that all variables are defined"
  tags:
    - assertion
  assert:
    that:
      - vars['metalk8s_storageclass_' ~ item.key] is defined
      - vars['metalk8s_storageclass_default_' ~ item.key] is defined
      - vars['metalk8s_host_path_' ~ item.key] is defined
  with_dict: '{{ metalk8s_lvm_managed_vgs }}'


- name: "Setup MetalK8S Storage: Update the LVM with hostpath and storageclass info"
  set_fact:
    metalk8s_kube_lvm_storage: >-
      {
        {%- for lv_path, lv_prop in metalk8s_lvm_all_lvs.items() -%}
          '{{ lv_path }}': {{ lv_prop|combine({
            'host_path': vars['metalk8s_host_path_' ~ lv_prop.vg_name],
            'storageclass': vars['metalk8s_storageclass_' ~ lv_prop.vg_name],
            'storageclass_default': vars['metalk8s_storageclass_default_' ~ lv_prop.vg_name],
            }) }},
        {%- endfor -%}
      }

- name: 'Setup MetalK8S Storage: Create dir for LVM storage'
  file:
    dest: '{{ item.value.host_path }}'
    state: directory
  with_dict: '{{ metalk8s_kube_lvm_storage }}'

- name: 'Setup MetalK8S Storage: Mount filesystem for each LVM LVs'
  mount:
    path: '{{ item.value.host_path }}/{{ item.value.uuid }}'
    src: UUID={{ item.value.uuid }}
    opts: '{{ item.value.mount_opts }}'
    fstype: '{{ item.value.fstype }}'
    state: mounted
  with_dict: '{{ metalk8s_kube_lvm_storage }}'
