apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: es-exporter-elasticsearch-exporter
  labels:
    app: elasticsearch-exporter
    prometheus: kube-prometheus
    release: es-exporter
spec:
  selector:
    matchLabels:
      app: elasticsearch-exporter
      release: es-exporter
  namespaceSelector:
    matchNames:
      - kube-ops
  endpoints:
  - port: http
