---
apiVersion: v1
kind: Pod
metadata:
  name: build-pod
spec:
  containers:
    - name: build-worker
      image: {{ images['docker-builder'] }}
      command: ["/bin/sh"]
      args: ["-c", "buildbot-worker create-worker . ${BUILDMASTER}:${BUILDMASTER_PORT} ${WORKERNAME} ${WORKERPASS} && buildbot-worker start --nodaemon"]
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: 500m
          memory: 2Gi
      env:
        - name: DOCKER_HOST
          value: localhost
      volumeMounts:
        - name: worker-workspace
          mountPath: /home/eve/workspace
    - name: platform-dind-daemon
      image: docker:18.09.2-dind
      resources:
        requests:
          cpu: 500m
          memory: 500Mi
        limits:
          cpu: 500m
          memory: 500Mi
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-storage
          mountPath: /var/lib/docker
        - name: worker-workspace
          mountPath: /home/eve/workspace
  volumes:
    - name: docker-storage
      emptyDir: {}
    - name: worker-workspace
      emptyDir: {}
