apiVersion: v1
kind: Pod
metadata:
  name: "metalk8s-pep8"
spec:
  containers:
  - name: worker-pep8
    image: {{ images['pep8-checker'] }}
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
    securityContext:
      capabilities:
        drop:
        - ALL
      # user -> 1000
      runAsUSer: 1000
    command: ["/bin/sh"]
    args: ["-c", "buildbot-worker create-worker . ${BUILDMASTER}:${BUILDMASTER_PORT} ${WORKERNAME} ${WORKERPASS} && buildbot-worker start --nodaemon"]
