{%- from "metalk8s/registry/macro.sls" import build_image_name with context -%}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: ui
    kubernetes.io/name: "MetalK8sUI"
spec:
  selector:
    matchLabels:
      k8s-app: ui
  template:
    metadata:
      labels:
        k8s-app: ui
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: metalk8s-ui
          image: {{ build_image_name('metalk8s-ui', '0.2') }}
          resources:
            limits:
              memory: 170Mi
            requests:
              cpu: 100m
              memory: 70Mi
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
