apiVersion: v1
kind: Pod
metadata:
  name: {{ name | default("metalk8s-unit-tests-worker") }}
spec:
  containers:
  - name: worker
    image: {{ images['docker-unit-tests'] }}
    resources:
      requests:
        cpu: {{ cpu_requests | default('500m') }}
        memory: {{ mem_requests | default('1Gi') }}
      limits:
        cpu: {{ cpu_limits | default('"1"') }}
        memory: {{ mem_limits | default('2Gi') }}
    command: ["/bin/sh"]
    args: ["-c", "buildbot-worker create-worker . ${BUILDMASTER}:${BUILDMASTER_PORT} ${WORKERNAME} ${WORKERPASS} && buildbot-worker start --nodaemon"]
    volumeMounts:
      - name: worker-workspace
        mountPath: /home/eve/workspace
  volumes:
    - name: worker-workspace
      emptyDir: {}
