apiVersion: v1
kind: Pod
metadata:
  name: {{ name | default("metalk8s-unit-tests-worker") }}
spec:
  containers:
  - name: worker
    image: {{ images['docker-unit-tests'] }}
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
    command: ["/bin/sh"]
    args: ["-c", "buildbot-worker create-worker . ${BUILDMASTER}:${BUILDMASTER_PORT} ${WORKERNAME} ${WORKERPASS} && buildbot-worker start --nodaemon"]
    volumeMounts:
      - name: worker-workspace
        mountPath: /home/eve/workspace
  volumes:
    - name: worker-workspace
      emptyDir: {}
