version: "0.2"

branches:
  default:
    stage: "pre-merge"

stages:
  pre-merge:
    worker: &pod
      type: kube_pod
      path: eve/workers/zenko.yaml
    steps:
    - TriggerStages:
        name: All pre-merge stages
        stage_names:
        - prechecks
        - single-node

  prechecks:
    worker: *pod
    steps:
    - Git: &git_pull
        name: git pull
        repourl: "%(prop:git_reference)s"
        mode: full
        method: clobber
        retryFetch: true
        haltOnFailure: true
    - ShellCommand:
        name: 'Check DCO signature'
        haltOnFailure: true
        command: sh ./hack/check-dco

  single-node:
    worker: &openstack
      type: openstack
      image: CentOS 7 (PVHVM)
      flavor: general1-4
    steps:
    - Git: *git_pull
    - ShellCommand:
        name: 'Run test-suite'
        haltOnFailure: true
        command: |-
          bash ./vendor/bash_unit/bash_unit tests/single-node/test.sh
