version: "0.2"

branches:
  default:
    stage: "pre-merge"

stages:
  pre-merge:
    worker: &pod
      type: kube_pod
      path: eve/workers/zenko.yaml
    steps:
    - TriggerStages:
        name: Build docs
        haltOnFailure: true
        stage_names:
        - build-doc
    - TriggerStages:
        name: trigger all the tests
        haltOnFailure: true
        stage_names:
        - single-node

  single-node:
    worker: &openstack
      type: openstack
      image: CentOS 7 (PVHVM)
      flavor: io1-30
      path: eve/workers/centos7_tests
    steps:
    - Git: &git_pull
        name: git pull
        repourl: "%(prop:git_reference)s"
        mode: full
        method: clobber
        retryFetch: true
        haltOnFailure: true
    - ShellCommand:
        name: 'Check syntax'
        haltOnFailure: true
        command: |-
          tox -e pep8
    - ShellCommand:
        name: 'Init node'
        haltOnFailure: true
        command: |-
          sudo bash eve/tests/single-node/init.sh
    - ShellCommand:
        name: 'Run the install test suite'
        haltOnFailure: true
        usePTY: true
        command: |-
          tox -e tests -- install -s
        env:
          ANSIBLE_INVENTORY: eve/tests/single-node/inventory/hosts
    - ShellCommand:
        name: 'Run the post-install test suite'
        haltOnFailure: true
        usePTY: true
        command: |-
          tox -e tests -- post -s --run-services
        env:
          ANSIBLE_INVENTORY: eve/tests/single-node/inventory/hosts

  build-doc:
    worker:
      type: kube_pod
      path: eve/workers/doc-builder.yaml
      images:
        doc-builder:
          context: '.'
          dockerfile: docs/Dockerfile
    steps:
    - Git: *git_pull
    - ShellCommand:
        name: 'Build doc'
        command: tox --workdir /tmp/tox -e docs -- html latexpdf
