version: "0.2"

branches:
  default:
    stage: "pre-merge"

stages:
  pre-merge:
    worker: &pod
      type: kube_pod
      path: eve/workers/zenko.yaml
    steps:
    - TriggerStages:
        name: trigger all the tests
        stage_names:
        - single-node
        - build-doc-inter-stage

  single-node:
    worker: &openstack
      type: openstack
      image: CentOS 7 (PVHVM)
      flavor: general1-4
      #path: eve/workers/centos7
    steps:
    - Git: &git_pull
        name: git pull
        repourl: "%(prop:git_reference)s"
        mode: full
        method: clobber
        retryFetch: true
        haltOnFailure: true
    - ShellCommand:
        name: 'create loopback blockdevice and configure VM'
        haltOnFailure: true
        command: |-
          sudo ./eve/single_node/setup/single_node.sh
    - ShellCommand:
        name: 'Create virtual env'
        haltOnFailure: true
        command: |-
          make shell
    - ShellCommand:
        name: 'Run the install with ansible'
        haltOnFailure: true
        command: >-
          ./.shell-env/metal-k8s/bin/ansible-playbook
          -i eve/single_node/
          metal-k8s.yml --skip elasticsearch
        env:
          ANSIBLE_FORCE_COLOR: 'true'
    - ShellCommand:
        name: 'Run sample kubectl command'
        haltOnFailure: true
        command: |-
            export PATH=${PATH}:/usr/local/bin
            kubectl get nodes
        env: &env_kubeconfig
          KUBECONFIG: inventories/single-node-ci/artifacts/admin.conf
    - ShellCommand:
        name: 'Test storage'
        haltOnFailure: true
        command: |-
            export PATH=${PATH}:/usr/local/bin
            make test-simple-storage
        workdir: build/tests
        env: *env_kubeconfig
    - ShellCommand:
        name: 'Verify that some pv are in released state'
        command: |-
          export PATH=${PATH}:/usr/local/bin
          kubectl get pv
          kubectl get pv -o jsonpath={.items[*].status.phase} | grep 'Released' > /dev/null
        env: *env_kubeconfig
    - ShellCommand:
        name: 'Reclaim storage'
        haltOnFailure: true
        command: >-
          ./.shell-env/metal-k8s/bin/ansible-playbook
          -i eve/single_node/
          reclaim-storage.yml
        env:
          ANSIBLE_FORCE_COLOR: 'true'
    - ShellCommand:
        name: 'Verify that no pv are in released state'
        command: |-
          export PATH=${PATH}:/usr/local/bin
          kubectl get pv
          ! kubectl get pv -o jsonpath={.items[*].status.phase}| grep 'Released' > /dev/null
        env: *env_kubeconfig

  build-doc-inter-stage:
    worker:
      type: kube_pod
      path: eve/workers/zenko.yaml
    steps:
    - TriggerStages:
        name: Stage to defer the build of docker of doc-builder
        stage_names:
        - build-doc

  build-doc:
    worker:
      type: kube_pod
      path: eve/workers/doc-builder.yaml
      images:
        doc-builder: docs/
    steps:
    - Git: *git_pull
    - ShellCommand:
        name: 'Build doc'
        command: make -C docs html
