- name: 'Setup MetalK8S StoracgeClass: Create storage addon dir'
  file:
    path: '{{ metalk8s_storage_addon_dir }}'
    owner: root
    group: root
    mode: 0755
    state: directory
    recurse: true
  run_once: True

- name: 'Setup MetalK8S StoracgeClass: Create storage-class manifests'
  template:
    src: local-storageclass.yml.j2
    dest: '{{ metalk8s_storage_addon_dir }}/storage-class-{{ item.key }}.yml'
  with_dict: '{{ metalk8s_kube_lvm_storage }}'
  run_once: True

- name: 'Setup MetalK8S StoracgeClass: Apply manifests for storage-class'
  kube:
    kubectl: '{{ bin_dir }}/kubectl'
    filename: '{{ metalk8s_storage_addon_dir }}/storage-class-{{ item.key }}.yml'
    state: 'latest'
  with_dict: '{{ metalk8s_kube_lvm_storage }}'
  run_once: True

- name: 'Setup MetalK8S StoracgeClass: Create pv manifests'
  template:
    src: local-pv.yml.j2
    dest: '{{ metalk8s_storage_addon_dir }}/pv-{{ item.value.volume.uuid }}.yml'
  with_dict: '{{ metalk8s_kube_lvm_storage }}'

- name: 'Setup MetalK8S StoracgeClass: Apply manifests for pv'
  kube:
    kubectl: '{{ bin_dir }}/kubectl'
    filename: '{{ metalk8s_storage_addon_dir }}/pv-{{ item.value.volume.uuid }}.yml'
    state: 'latest'
  with_dict: '{{ metalk8s_kube_lvm_storage }}'
