# The role default variable are not present in hostvars[inventory_hostname]
# https://github.com/ansible/ansible/issues/6189
# We then rely on "vars" which "works" but not happy about it
- name: "Setup MetalK8s Storage: Check that VG variables are defined"
  tags:
    - assertion
  assert:
    that:
      - vars['metalk8s_storageclass_' ~ item] is defined
  with_items: '{{ metalk8s_lvm_vgs }}'

- name: 'Setup MetalK8s StorageClass: Create storage addon dir'
  file:
    path: '{{ metalk8s_storage_addon_dir }}'
    owner: root
    group: root
    mode: 0755
    state: directory
    recurse: true

- name: 'Setup MetalK8s StorageClass: Create StorageClass manifests'
  template:
    src: local-storageclass.yml.j2
    dest: '{{ metalk8s_storage_addon_dir }}/storage-class-{{ vars["metalk8s_storageclass_" ~ item] }}.yml'
  with_items: '{{ metalk8s_lvm_vgs }}'

- name: 'Setup MetalK8s StorageClass: Apply manifests for StorageClass'
  kube:
    kubectl: '{{ bin_dir }}/kubectl'
    filename: '{{ metalk8s_storage_addon_dir }}/storage-class-{{ vars["metalk8s_storageclass_" ~ item] }}.yml'
    state: 'latest'
  with_items: '{{ metalk8s_lvm_vgs }}'
  run_once: True

- name: 'Setup MetalK8s StorageClass: Create pv manifests'
  template:
    src: local-pv.yml.j2
    dest: '{{ metalk8s_storage_addon_dir }}/pv-{{ item.value.uuid }}.yml'
  with_dict: '{{ metalk8s_lvm_all_lvs }}'

- name: 'Setup MetalK8s StorageClass: Apply manifests for pv'
  kube:
    kubectl: '{{ bin_dir }}/kubectl'
    filename: '{{ metalk8s_storage_addon_dir }}/pv-{{ item.value.uuid }}.yml'
    state: 'latest'
  with_dict: '{{ metalk8s_lvm_all_lvs }}'
  run_once: True
