---
- hosts: localhost
  gather_facts: False
  any_errors_fatal: '{{ any_errors_fatal | default(true) }}'
  roles:
    - role: preflight_checks
  tags:
    - preflight-checks

- name: Check node access
  hosts: k8s-cluster:etcd
  gather_facts: true
  any_errors_fatal: '{{ any_errors_fatal | default(true) }}'
  roles:
    - role: node-access-checks
      vars:
        node_access_checks__remote_groups:
          - k8s-cluster
          - etcd
  tags: ['role::node-access-checks']

- hosts: k8s-cluster:etcd
  roles:
    - role: check_os

- hosts: k8s-cluster:etcd
  any_errors_fatal: '{{ any_errors_fatal | default(true) }}'
  roles:
    - role: '../vendor/ansible-hardening'
      when: metalk8s_ansible_hardening_enabled | default(true) | bool
  vars:
    security_rhel7_enable_linux_security_module: false
  tags:
    - ansible-hardening

- hosts: k8s-cluster
  any_errors_fatal: '{{ any_errors_fatal | default(true) }}'
  roles:
    - role: prepare_os
